name: gtu_bike
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_barcode_scanner: ^2.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  animated_text_kit: ^4.2.1
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  modal_progress_hud: ^0.1.3
  fluttertoast: ^8.0.8
  dart_date: ^1.1.0
  rflutter_alert: ^2.0.4
  mailer: ^5.0.2
  google_sign_in: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
